feat: add safe rm

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -145,3 +145,12 @@ then
     exec fish $LOGIN_OPTION
 fi
 # <<< fishshell <<<
+
+# Prevent accidental deletion of root directory
+rm() {
+    if [[ "$*" =~ -[rf].*[[:space:]]/[[:space:]]* ]] || [[ "$*" =~ [[:space:]]/[[:space:]].*-[rf] ]]; then
+        echo "Error: Deletion of root directory is prohibited" >&2
+        return 1
+    fi
+    command rm "$@"
+}
